Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Player.Models;
using Microsoft.Extensions.Logging;
using Player.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace Player.Controllers
{
    public class PlaylistController : Controller
    {
        private readonly AuthDbContext _context;

        public PlaylistController(AuthDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            List<Playlist> playlists = (from x in _context.Playlist where x.userID == currentUserID select x).ToList();
            ViewData["playlists"] = playlists;
            return View();
        }
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var playlist = _context.Playlist.Find(id);

            ViewData["playlistId"] = playlist.PlaylistId;
            ViewData["playlistName"] = playlist.Name;
            return View(playlist);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Playlist playlist)
        {
            try
            {
                ClaimsPrincipal currentUser = this.User;
                var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
                var renamedPlaylist = _context.Playlist.Find(playlist.PlaylistId);
                renamedPlaylist.Name = Request.Form["playlistName"];

                if (renamedPlaylist.userID == currentUserID)
                {
                    _context.Entry(renamedPlaylist).State = EntityState.Modified;
                    _context.SaveChanges();
                }
            } catch
            {

            }

            Index();
            return View("Index");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Playlist playlist)
        {

            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            playlist.userID = currentUserID;
            _context.Add(playlist);
            _context.SaveChanges();

            Index();
            return View("Index");
        }

        [Authorize]
        public ViewResult Detail(int id)
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            Playlist playlist = _context.Playlist.Find(id);

            if(playlist != null)
            {
                if (playlist.userID == currentUserID)
                {
                    List<SongPlaylist> songplaylist = (from x in _context.SongPlaylist where x.PlaylistId == id select x).Include(q => q.Song).ToList();

                    ViewData["songs"] = songplaylist;
                    ViewData["playlistName"] = playlist.Name;
                    ViewData["playlistId"] = playlist.PlaylistId;
                    return View(playlist);
                }
                else
                {
                    Index();
                    return View("Index");
                }
            }
            else
            {
                Index();
                return View("Index");
            }
        }


        [HttpPost]
        public IActionResult RemoveSong()
        {
            try
            {
                var playlistId = Int32.Parse(Request.Form["playlistId"]);
                var songId = Int32.Parse(Request.Form["songId"]);
                var song = _context.Set<SongPlaylist>().Where(x => x.PlaylistId == playlistId && x.SongId == songId).FirstOrDefault();

                if (song != null)
                {
                    _context.Set<SongPlaylist>().Remove(song);
                    _context.SaveChanges();
                }
                return RedirectToAction("Edit", new { id = playlistId });
            } 
            catch 
            {
                Index();
                return View("Index");
            }
        }

        [HttpPost]
        public IActionResult Remove()
        {
            try
            {
                var playlistId = Int32.Parse(Request.Form["playlistId"]);
                var playlist = _context.Playlist.Find(playlistId);
                _context.Playlist.Remove(playlist);
                _context.SaveChanges();
            }catch { }

            Index();
            return View("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Player</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/layout.css" />
    <link rel="stylesheet" href="~/css/songs.css" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Player</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Playlist" asp-action="Index">Playlists</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial.cshtml" />
                <i class="material-icons" id="btn_theme">
                    brightness_3
                </i>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="player" hidden>
        <div id="music_player_box">
            <div>
                <i class="material-icons skip" id="skip_previous">skip_previous</i>
                <i class="material-icons music_buttons" id="play_button">pause</i>
                <i class="material-icons  skip" id="skip_next">skip_next</i>
            </div>
            <br />
            <div id="div_bottom_buttons">
                <i class="material-icons music_buttons" id="less_volume">volume_down</i>
                <i class="material-icons music_buttons" id="mute_button">volume_off</i>
                <i class="material-icons music_buttons" id="more_volume">volume_up</i>
            </div>
        </div>
        <div id="right_player">
            <div id="music_player"></div>
            <p id="title_player"></p>
        </div>
    </div>
    <div id="playerNoHide" hidden></div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2021 - Player
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/gh/fcmam5/nightly.js@v1.0/dist/nightly.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/wavesurfer.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <!-- music player -->
    <script src="~/js/music.js"></script>




</body>
</html>