Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Player.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Player.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Data.AuthDbContext _context;

        public HomeController(ILogger<HomeController> logger, Data.AuthDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            List<Song> songs = _context.Song.ToList();
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Playlist> playlists = (from x in _context.Playlist where x.userID == currentUserID select x).ToList();

            ViewData["playlists"] = playlists;
            ViewData["songs"] = songs;
            return View();
        }

        [Authorize]
        public IActionResult AddSong()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddSongPlaylist(SongPlaylist songPlaylist)
        {
            try
            {
                //SongPlaylist songPlaylist = new SongPlaylist();

                var selected_playlist = Request.Form["selected_playlist"];
                Playlist playlist = _context.Playlist.Find(Int32.Parse(selected_playlist));

                var selected_song = Request.Form["songId"];
                Song song = _context.Song.Find(Int32.Parse(selected_song));

                songPlaylist.PlaylistId = playlist.PlaylistId;
                songPlaylist.SongId = song.SongId;

                _context.Add(songPlaylist);
                _context.SaveChanges();
            } catch {

            }

            Index();
            return View("Index");
        }
    }
}

Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Player.Models;
using Microsoft.Extensions.Logging;
using Player.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Diagnostics;
using System.Security.Claims;

namespace Player.Controllers
{
    public class SongController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;

        public SongController(AuthDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            hostingEnvironment = environment;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Song song)
        {
            try
            {
                List<String> listExt = new List<String>() { "mp3", "wav", "m4a", "flac", "mp4", "wma", "aac" };
                var Files = Request.Form.Files;

                foreach (var file in Files)
                {
                    var songs = Path.Combine(hostingEnvironment.WebRootPath, "songs");
                    if (file.Length > 0)
                    {
                        string filename = Guid.NewGuid().ToString();
                        var old_filename = file.FileName.Split('.');
                        var extension = old_filename.Last().ToLower();

                        if (listExt.Contains(extension) == false)
                        {
                            ViewData["error_file_type"] = "You have send a non authorized type file";
                            return View();
                        }

                        song.PathFileSong = filename + "." + extension;
                        using (var fileStream = new FileStream(Path.Combine(songs, song.PathFileSong), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        _context.Add(song);
                        _context.SaveChanges();
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
         
        }

        public IActionResult Detail(int id)
        {
            var song = _context.Song.Find(id);

            ViewData["songTitle"] = song.Title;
            ViewData["songArtist"] = song.Artist;
            ViewData["songGenre"] = song.Genre;
            return View();
        }


        public IActionResult AddInPlaylist(int id)
        {
            var song = _context.Song.Find(id);
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Playlist> playlists = (from x in _context.Playlist where x.userID == currentUserID select x).ToList();

            ViewData["playlists"] = playlists;
            ViewData["songName"] = song.Title;
            ViewData["songId"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddInPlaylist(SongPlaylist songPlaylist)
        {
            try
            {
                //SongPlaylist songPlaylist = new SongPlaylist();

                var selected_playlist = Request.Form["selected_playlist"];
                Playlist playlist = _context.Playlist.Find(Int32.Parse(selected_playlist));

                var selected_song = Request.Form["songId"];
                Song song = _context.Song.Find(Int32.Parse(selected_song));

                songPlaylist.PlaylistId = playlist.PlaylistId;
                songPlaylist.SongId = song.SongId;

                _context.Add(songPlaylist);
                _context.SaveChanges();
            }
            catch
            {

            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Delete()
        {
            try
            {
                var songId = Request.Form["songId"];
                var song = _context.Song.Find(Int32.Parse(songId));
                _context.Song.Remove(song);
                _context.SaveChanges();
            }
            catch { }

            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Songs</h1>

    <table id="songTable" class="display">
        <a type="button" class="btn btn-primary" id="button_add_song" asp-controller="Song" asp-action="Create">Add Song</a>
        <thead>
            <tr>
                <th>Lire</th>
                <th>Titre</th>
                <th>Artiste</th>
                <th>Genre</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Player.Models.Song song in ViewData["songs"] as List<Song>)
            {
                <tr>
                    <td class="SongItemPlay" data-path="@song.PathFileSong" data-title="@song.Title" data-artist="@song.Artist"><i class="material-icons">play_arrow</i></td>
                    <td class="SongItem">@song.Title</td>
                    <td class="SongItem">@song.Artist</td>
                    <td class="SongItem">@song.Genre</td>
                    <td class="d-flex float-right">
                        <!-- Go to detail -->
                        <a hidden type="button" class="goDetail" asp-controller="Song" asp-action="Detail" asp-route-id="@song.SongId">Detail</a>
                        <i class="material-icons btnSongIcons btnSong btnDetail">info</i>
                        <!-- Add in a playlist-->
                        <a hidden type="button" class="goAddPlaylist" asp-controller="Song" asp-action="AddInPlaylist" asp-route-id="@song.SongId">Add Song</a>
                        <i class="material-icons btnSongIcons btnSong btnAdd">add</i>
                        <!-- Delete song -->
                        <form method="post" action="@Url.Action("Delete", "Song")">
                            <input type="hidden" name="songId" value="@song.SongId" />
                            <i class="material-icons btnSongIcons btnSongDelete">clear</i>
                        </form>
                    </td>
                </tr>
            }

        </tbody>
    </table>


    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready(function () {
            $('#songTable').DataTable(
            );
        });
    </script>
</div>